trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildOutput: '.dist'

steps:
- script: dotnet publish --configuration $(buildConfiguration) --output $(buildOutput)
  displayName: 'Publish Blazor Site'

# Deploy the wwwroot
# The argument "--prod" deploys to  
- script: |
    npm install netlify-cli 
    npx netlify deploy --prod --dir $(buildOutput)/wwwroot --site $(netlify_site_id) --auth $(netlify_api_key)
  displayName: 'netlify deploy'